### ISSUE TITLE
Task Listing under Case Item - Shows all open tasks not just for the selected case

### ISSUE THREAD

**Issue by desbigi** [desbigi/DRS#1]
When you're in Case Details
http://pmsvault.com/DSIProject/Cases/Details/2
and select Open tasks (or any other option) it displays ALL open tasks - it should only display the Open tasks of the Case we are looking at

![image](https://cloud.githubusercontent.com/assets/9138038/24514192/53fc3a84-156b-11e7-8091-0988ec07de49.png)

**Comment by BernieCrilly** [comment]
In screen above, the 'Open' filter should display Open tasks for that Case only.
Case 2, shown above, has only 1 task, Task ID 2.  If you select 'Open' it should still display Task 2 only - but instead it displays ALL the open tasks on the system...(same for Urgent / Completed / All)
