### ISSUE TITLE
Reporting requirements - Summary Report 

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#10]
Phase 1 reporting requirements / effort  to be agreed before commencing work
Initial set of reports attached
[DSI Reports 2.docx](https://github.com/desbigi/DRS/files/933406/DSI.Reports.2.docx)

Export capability to be included

**Comment by cojocarus** [comment]
Report deployed, there's an issue with exporting the report, will comment again here, after I fix it.

**Comment by BernieCrilly** [comment]
see #72
