### ISSUE TITLE
Case / Task listing - display Open only by default

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#12]
When a Team member logs on daily, they will be presented with a list of outstanding Tasks that have been assigned to that user- this should display open tasks only  by default - with URGENT tasks appearing at the top of the list

**Comment by scojocaru** [comment]
And perhaps display the urgent ones with a visual hint to differentiate from the normal ones?

**Comment by BernieCrilly** [comment]
yes that would be helpful
