### ISSUE TITLE
DRS  / CHAMP Access - do we need a DRS only role in CHAMP?

### ISSUE THREAD

**Issue by desbigi** [desbigi/DRS#13]
Ilya can you give a brief description of access currently define by this tick box. 
![image](https://cloud.githubusercontent.com/assets/9138038/25177476/1c01306e-24fa-11e7-8035-81cf6757b281.png)

?
Will These use be restricted in their CHAMP access - perhaps Role is the next level of controlled access? 
eg - they Can see all of DRS Data, but only CHAMP access as defined. above??

@BernieCrilly @scojocaru

**Comment by BernieCrilly** [comment]
Can we clarify:
3 types of users (team members not Service Users)
1.  CHAMP only, no access to DRS - we have covered that above, DRS access not ticked
2.  CHAMP & DRS - as above - existing CHAMP access level determines CHAMP permissions; DRS login determines what they can see there withe the exception of the Administrator with DRS access who can see everything in DRS.  
(Is there a possibility that a user with CHAMP Administrator role should only have DRS access determined by their login, eg if several CHAMP users have Administrator Role but only the overall Admisistrator should have full access (view) of DRS? - we will wait to see if this comes up from client)
3.  DRS only - no access to CHAMP.  so do we need another CHAMP role ie DRS only to be able to do this?

**Comment by BernieCrilly** [comment]
can now assign access to DRS only / CHAMP only / select access level for either or both
