### ISSUE TITLE
Roles usage

### ISSUE THREAD

**Issue by scojocaru** [desbigi/DRS#24]
Please describe how Roles (http://pmsvault.com/DSIProject/Roles) should be used in the app.
Below an image, thanks to Des:
![image](https://cloud.githubusercontent.com/assets/3381981/25457866/a4ca16d8-2acf-11e7-8d77-1a3b9e229138.png)

**Comment by BernieCrilly** [comment]
Hi Sergei - met with Des this morning and we talked over this.  The 'role' field was not an original request from the client - it was something we added on, it is purely descriptive and doesn't feed in anywhere else.  We have decided for now that best / easiest solution is to hide it completely.  DSI don't need it as they have a small number of support workers who all know each other.  We may decide to revisit it in the future for another client
