### ISSUE TITLE
Close task / case functionality

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#3]
**TASKS**
1.  When a task is closed NO changes can be made - maybe we should include a message to the user asking them to verify that they wish to close the task

2.  Re closing a task - User can either:
Check ' Completed' checkbox - this should auto-populate the date Closed with today's date - although user can edit if required
OR
User enters Date Closed - this automatically checks the 'Completed' box
So the 'completed' check box and the Date Closed are linked and must be consistent

3.  If the last open task is closed - offer user option to either close case or open a new task for example

![image](https://cloud.githubusercontent.com/assets/26797063/24526886/bbff8420-1597-11e7-8af0-bbf4c2db7154.png

**CASES**
1.  A Case cannot be closed if there are open tasks AND if there are no open tasks the case should be closed SO
Following this logic, we don't need the 'Completed' tick box on the Edit Case screen - the Case can only be completed when the last task has been completed as outlined above

2.  There can be no changes to a closed Case

**Comment by scojocaru** [comment]
I think we should add more rules for a completed task:
 - Closed date to be mandatory when marking a task as completed (and not in the future)
 - What operations could be performed on a completed task, if any (you can assign it to another person
currently and so on, which seems to be wrong)
