### ISSUE TITLE
Flag for DRS users in CHAMP

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#31]
As discussed previously (don't think on GIT yet?) - need some way of identifying DRS usesr from ordinary donors / members.  We talked about using the 'type' as a way of doing this.  Was this agreed?  Or if not how will we do this?

**Comment by QuasiChe** [comment]
'Type' is a bad idea. When adding DRS cases to existing donor/member should we change type? 
I suggest to show DRS with icon on one of these locations. Or both, if you wish.
![clipboard01](https://cloud.githubusercontent.com/assets/13958648/26457395/9c8f3af6-4178-11e7-8208-df0ad36fe3be.png)
First group of icons indicates type of CSI membership, shopper, event attendee, volunteer.
Second location shows if donor/member is also a lottery participant.
I can add an icon indicating if a donor/member also has information in DRS.

**Comment by BernieCrilly** [comment]
Yes, I like the idea of the icon.
So to clarify...(I don't have acccess to DSI at the minute so can't look.....) - do all existing records on CHAMp have an icon - ie either member  or donor or both (maybe DSI is donor only?)
So if existing member uses system they will have member icon and DRS icon
If a new Service User uses DRS - they will have the DRS icon only (unless they later become a donor at some point..)....and so these DRS people will be automatically excluded from any campaigns, mailshots etc.....

**Comment by QuasiChe** [comment]
No, most of DSI donors/members do not have any icons. Icons for membership types are used for CSI only.
> and so these DRS people will be automatically excluded from any campaigns, mailshots etc.....

Wait a minute. Until now we spoke about some 'indication'.
I suggested to indicate when a donor has some additional info in DRS. This does not imply donor was created in DRS and/or does not have any information in Fundraising. This indication will not automatically exclude donor from mailshots.
So, what is your task? Exclude from campaigns and mailshots those who are DRS-only and do not have any fundraising - correct or not? If this is the task, it should be done with contact preferences. When donor is created in DRS all contact preferences should be set to 'Off' - then he will not be included in mailshots. If some fundraising is later added for this donor, users should manually permit some contact options.

**Comment by BernieCrilly** [comment]
I think we will need to identify those who used the referral system only, for example, I imagine one of the stats they might want to look at is how many referrals are from existing CHAMP members and how many are from non CHAMP users

We should do as you suggest re contact preferences but I think we need to identify them as DRS only also

**Comment by QuasiChe** [comment]
> but I think we need to identify them as DRS only also

Ok, but we need to define clearly what does "DRS **only**" mean.
Does it mean they have no money transactions? Almost 12k donors/members (~75%) in DSI database do not have money transactions, so this is not a criteria.
Or, in other words, what should happen to "DRS only" record to become a "not only DRS" record?

**Comment by BernieCrilly** [comment]
HI Ilya - I am trying to think what information might be useful to client
or what they might want to know from system...

For example, to see how many referrals come from people who are already in
CHAMP... and how many are from people that have had no previous interaction
with....the DRS-only means the original source of contact was via DRS so
they could see this


Example, If a person has a new case then the DRS flag is on

The next month they have another new case - if DRS flag is on they are
being double-counted a a 'new user'  but if we turn DRS flag off on a
second case - do then lose the information that the original contact was
via DRS?
So to identify a 'new' user we would need to check if DRS flag is on AND
this is the first case...

Seems to be getting more complicated and I don't want to make a big deal
out of it but just want to be sure that we capture all information the
client might come looking for later.  Also I am not 100% familiar with DSI
and what information will be important to them.  Maybe I need to check back
with client / Des...

**Comment by QuasiChe** [comment]
Hi Bernie.
I was confused by terminology "DRS only", thought it should reflect current record state.
Now I see that you only want to store record source - was the person record originally created in Champ or in DRS. Yes, this can be easily done. When record is updated, we will not change this flag, so there will be no transition between these categories.
> The next month they have another new case ...

It is DRS responsibility to distinguish new and recurring persons, in this situation DRS should open new case for existing person.

**Comment by BernieCrilly** [comment]
Updated requirement - just been talking over with Des - need 2 flags on this:
1 History note in Donor record to say 'Created in DRS with date time by ...etc' - all contact preferences switched off
2 Indicator / flag that they have used the referral system - you had mentioned an icon previously (above) or apply keyword..??
3 Also, a new 'type' of Contact - so they are not set up as a Donor.  If they do become a donor in the future, the type should be changed

**Comment by BernieCrilly** [comment]
![image](https://user-images.githubusercontent.com/26797063/30166351-f4cda536-93da-11e7-80f4-c97914894210.png)

**Comment by BernieCrilly** [comment]
Hi Ilya
I have updated note on this in GIT

**Comment by QuasiChe** [comment]
Do we have some logo for DRS system? Or a favicon?

**Comment by QuasiChe** [comment]
Implemented.
