### ISSUE TITLE
remove top Label of Client Search or make it white on purple to show it is heading

### ISSUE THREAD

**Issue by desbigi** [desbigi/DRS#37]
![image](https://user-images.githubusercontent.com/9138038/28683712-77d3445c-72f9-11e7-9f5a-30dcc4e6e8cf.png)

**Comment by scojocaru** [comment]
Made it purple, available next deploy

**Comment by desbigi** [comment]
Different ticket but can I request ui Change.  

U set notes heading it says edit. (Logic ok) but can we make this day 'Notes' instead or use and eye icon perhaps. As that would be more intuitive.  

Also case on the left of the listing  is a bit counter intuitive.  Can you move that towards the extreme right, see what looks good.  
I refer to task listing, so think this will not be the first step for the user. 
Not urgent but open to view and see what works 

Thank 
D
