### ISSUE TITLE
Changes to New Service User screen

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#4]
Remove Gender - not stored on CHAMP so no point in having it here
Remove duplicate Title field

Fields should correspond with CHAMP, to include:
First name
Last name
Title (add 'Ms' as selection in Title (add Rev / Fr / Sr))
Address 1
Address 2
Address 3
Town
County (from dropdown see #9)
Eircode?
Phone 1
Phone 2
Email

Also, request to have 'Source' here as a dropdown list - select from Phone / Email / In person visit / During outside visit / (Conference / training) / Local branch - can you give indication of time required to add this before proceeding

**Comment by BernieCrilly** [comment]
Please add source as above - client request 👍 
dropdown list - select from Phone / Email / In person visit / During outside visit / (Conference / training) / Local branch

**Comment by desbigi** [comment]
EIRCODE will be import for Tuesday great if we can add please D

**Comment by BernieCrilly** [comment]
Not part of Phase 1
