### ISSUE TITLE
Allow UNKNOWN as county 

### ISSUE THREAD

**Issue by desbigi** [desbigi/DRS#41]
Perhaps for ilya to add to champ first. 
Currently DRS-dev will not allow empty and unknown is not listed. 
I think if added to champ db it will work fine.

**Comment by scojocaru** [comment]
Yes, this should be added to Champ first, if we go this way, or make it non-mandatory in DRS.

**Comment by desbigi** [comment]
Perhaps make it non mandatory.  
Later we can review.

**Comment by scojocaru** [comment]
Done.
