### ISSUE TITLE
Service User details screen - minor changes

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#42]
Sergiu
Can you change the Client Search on LHS back to previous - ie searching all of CHAMP.  When the Team member has found and selected a user -> both the Personal Details and the PWDS sections should be expanded at this stage - so the Team member has maximum information available - the list of Cases (if any) is visible also...

Also wondering about document visibility - at present no way to see if there is a document associated with a CaSe (apart from actually clicking on the Documents tab) - is there some way - icon or whatever - to show instantly if there is a document uploaded?

**Comment by cojocarus** [comment]
The documents tab will have something like this:
Documents([numberOfDocuments]), showing - Documents (0) or Documents (2).
Will be available on the next deployment. Also, I changed back to search entire Champ for:
 - Left side search
 - New case creation
