### ISSUE TITLE
DRS - Auto fill from Task Action Required - auto replicate in note 

### ISSUE THREAD

**Issue by desbigi** [desbigi/DRS#44]
![image](https://user-images.githubusercontent.com/9138038/29412846-415f59a6-8352-11e7-83b8-818f1c8f5871.png)

**Comment by scojocaru** [comment]
At the moment done as follows: 
If the user doesn't fill anything in Notes, when the task is saved (create/edit), action content is copied into Notes, otherwise notes content is saved.
