### ISSUE TITLE
Fix filter on Task list

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#53]
The 'Created by me' filter does not include tasks that are created by me and assigned to me. It should include these as they are still 'Created by me'

eg logged on as Des
select 'Assigned to me' - first task visible has been created by Des and assigned to Des...that's fine
if you select 'Created by me' and deselect 'Assigned to me' this does not appear....

**Comment by scojocaru** [comment]
Replaced with 2 dropdowns - status and assignment, mainly because deselecting both doesn't make sense.

**Comment by desbigi** [comment]
Just make sure this ui works on iPad /tablet.

**Comment by BernieCrilly** [comment]
Don't see these dropdowns Sergei?? is is deployed?
