### ISSUE TITLE
DSI - new type for DRS service users

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#55]
related to https://github.com/desbigi/DRS/issues/31

feedback from client 12 september. can we add a new Type 'Non-member' for new service users created in DRS

Can you do this asap as they are going to be using system immediately?
Thanks

**Comment by QuasiChe** [comment]
Implemented.
Type is called 'Contact' as requested in #31. Can rename if they want.
@[Sergiu](scojocaru), when you create new service user in DRS, please set `@Type` parameter to Comsol.Champ.DataLayer.CollectorTypes.DrsContact (numerical value is 11, but using symbolic constant is preferable).

**Comment by BernieCrilly** [comment]
HI Ilay - can you rename to Non-member please 
Thanks
