### ISSUE TITLE
Edit Case screen - fields to be non-editable

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#7]
The only change that can be made to Edit Case is to reassign it to another Team Member

Remove the 'New' service user option - not needed here
The Category and Subcategory cannot be changed via Edit Case as per request by client
Date Opened cannot be changed
Date Closed should only be populated when last Task marked completed #3 so user should nto be able to enter a Date Closed here

Once a case has been closed, it cannot be reopened - so nothing can be edited once closed

**Comment by scojocaru** [comment]
What about Case Summary field, can it be changed on Edit?

**Comment by BernieCrilly** [comment]
I'll come back to you on this
