### ISSUE TITLE
Add DRS icon to tab when window opened

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#71]
Can you add the little icon to tab for DRS

![image](https://user-images.githubusercontent.com/26797063/31231059-a9c0cbf4-a9dd-11e7-87f1-63bb1e90960a.png)

**Comment by scojocaru** [comment]
Please attach a good quality image, so I can make a good quality favicon from it.

**Comment by scojocaru** [comment]
Done, available after next deployment

**Comment by BernieCrilly** [comment]
looks great :-)
