### ISSUE TITLE
Case Summary

### ISSUE THREAD

**Issue by scojocaru** [desbigi/DRS#72]
Just to confirm my understanding:
Cases Open at start: cases with closed date at the start date or later
% Cases open at start: **not sure here**, need an example
Cases opened: cases opened between start and end date of the period (both inclusive)
Cases open at end: with closed date after end date period
Cases closed: cases closed between start and end date of the period (both inclusive)
...

Also, what the pie chart will display?

**Comment by BernieCrilly** [comment]
![image](https://user-images.githubusercontent.com/26797063/31383673-d2ea3dec-adb3-11e7-8b28-c28a6939b22f.png)


(ignore last 2 columns)
Does this clarify?  You have number cases open at start of month - then this is expressed as a percentage

so team member is able to say 18% of cases at start of month related to adult education, etc. -

**Comment by scojocaru** [comment]
Ok, thanks

**Comment by BernieCrilly** [comment]
Can't view detail of report in live DRS, can see top LH corner only  - is OK in DRS-Dev
![image](https://user-images.githubusercontent.com/26797063/31430439-bafc8d56-ae68-11e7-8deb-e363046a213d.png)

**Comment by BernieCrilly** [comment]
Report looks good - hard to test fully as I don't have access to data

When I export to Excel, would like to sort / filter - but there are blank lines and columns so can't do this - can these be removed? or are they needed for layout?

**Comment by scojocaru** [comment]
Fixed export functionality, deployed. 
For the export to excel, please post a screenshot.
