### ISSUE TITLE
CRS Search giving different results to CHAMP

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#76]
This is one of Annette's issues - and she did send an example of an issue:

Search John Connolly on CHAMP - returns 'John &  Marion Connolly' which is the person she was looking for - BUT enter John Connolly in CRS - it comes back empty - so obviously different search algorithm, doesn't seem to like the '&'

Can we use same search in CRS as in CHAMP so records can be found AND results are consistent

Thanks

**Comment by scojocaru** [comment]
Fixed, available after next deployment

**Comment by BernieCrilly** [comment]
workign fine
