### ISSUE TITLE
Issue re closing cases

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#77]
Annette says that sometimes when she is closing a few cases, she has to log out of the referral system after closing one, and then log back in again.  Seems very strange.  See email thread:

_Can I just check - you said you have to log out and go back in to close another case? Do you mean you have to log out of the referral system (which shouldn't be happening) or that you have to go back out to another screen?_

**I **have to log out of the referral system completely  I can only do one at a time.****

**I was doing some catch up on my calls, emails etc.,, last week and most tasks were completed at that point and  I opened a case, assigned a task I was able to close them as I went along but normally when a task is waiting to be completed and I finish something at a later date I can only close one at a time.**

Again, I will ask if she can provide more information or specific example as I imagine this would be hard to replicate

**Comment by scojocaru** [comment]
I cannot understand the comments, how does logout help and helps doing what?

**Comment by BernieCrilly** [comment]
I have asked her to provide an example.  I have never seen this happen so unless she comes back to us, I suggest we leave this.

it probably just timed out.
